### PR TITLE
Restructure guest/host error handling

### LINKED ISSUE #497: Confusing ERROR tracing when not actually an error
https://github.com/ludfjig/hyperlight/blob/vm_trait/src/hyperlight_common/src/flatbuffer_wrappers/guest_error.rs#L199

causes any failures to be logged with ERROR level. However, we use this function unconditionally to check whether an error occured or not here https://github.com/ludfjig/hyperlight/blob/vm_trait/src/hyperlight_host/src/func/guest_err.rs#L28

Thus if the function fails, it is not an error

### LINKED ISSUE #826: Memory Leak in Guest on Error Calling Host Function
### What happened?

This leak was uncovered in fuzzing. When a guest calls a host function, if there is an error calling the host function itself -- for example, the host function does not exist -- the error propagates on the host side and we never return back to the guest to allow it to unwind and drop any allocated resources. In the `fuzz_host_call` target, we are currently running into memory exhaustion because we try to execute many iterations of such faulty host calls on the same sandbox in sequence. 

### What did you expect to happen?

If there is any error produced in attempting to call a host function in the guest, we need to yield control back to the guest and trigger some kind of unwind.

### Steps to reproduce the behavior

1. Checkout the branch used in #818
2. Run `just guests; just fuzz fuzz_host_call`
3. Fuzzing should fail with a memory allocation error almost immediately

### Hyperlight Version

0.8.0

### OS version

<details>

```console
On Linux:
$ cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux user 6.6.87.2-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
````
</details>

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ludfjig**
This PR improves error handling between host and guest functions to prevent memory leaks and ensure more reliable deserialization.

Previously, when a host function (invoked from the guest) returned an error, the error was reported immediately without unwinding the guest stack. This left guest-side allocations in an inconsistent state, leading to memory leaks on subsequent entries into the guest.

In addition, error reporting relied on a fragile mechanism: guest errors were manually serialized into a buffer, and the host would attempt to detect them by trying to deserialize an error. If deserialization succeeded, an error was assumed to have occurred. This approach is risky because there was nothing preventing GuestError and FunctionCallResult from possibly having the same serialized format since they are completely separate.

Changes

- Guest/host function calls now always return a FunctionCallResult, which explicitly represents either Ok or Err.
- If host function returns an error, it's serialized back into the guest, and the guest will properly unwind, and report it back to the host, fixing a memory leak.

TODO: 

For C guests: If host function returns an error, guest will panic when trying to read an expected good value (because there is only an error instead), and leak memory as a result. Will fix this in follow up PR

Closes #826 
Closes #497

### CODE REVIEW

File: src/hyperlight_host/src/func/guest_err.rs [hunk 1]
```diff
@@ -1,48 +0,0 @@
...
-
-/// Check for a guest error and return an `Err` if one was found,
-/// and `Ok` if one was not found.
-pub(crate) fn check_for_guest_error(mgr: &mut MemMgrWrapper<HostSharedMemory>) -> Result<()> {
-    let guest_err = mgr.as_mut().get_guest_error().ok();
-    let Some(guest_err) = guest_err else {
-        return Ok(());
-    };
-
-    metrics::counter!(
```
Comment (jsturtevant) [inline src/hyperlight_host/src/func/guest_err.rs:35]: did we replace this metric?

File: src/hyperlight_guest_bin/src/guest_function/call.rs [hunk 2]
```diff
@@ -81,10 +82,12 @@ pub(crate) fn call_guest_function(function_call: FunctionCall) -> Result<Vec<u8>
 
 // This function is marked as no_mangle/inline to prevent the compiler from inlining it , if its inlined the epilogue will not be called
 // and we will leak memory as the epilogue will not be called as halt() is not going to return.
+//
+// This function may panic, as we have no other ways of dealing with errors at this level
```
Comment (jsturtevant) [inline src/hyperlight_guest_bin/src/guest_function/call.rs:86]: This seems like a tricky change, although the previous version looks to have just ignored errors?

File: src/hyperlight_host/tests/sandbox_host_tests.rs [hunk 3]
```diff
@@ -374,6 +374,7 @@ fn host_function_error() -> Result<()> {
             assert!(
                 matches!(&res, HyperlightError::GuestError(_, msg) if msg == "Host function error!") // rust guest
             || matches!(&res, HyperlightError::GuestAborted(_, msg) if msg.contains("Host function error!")) // c guest
+            || matches!(&res, HyperlightError::StackOverflow()) // c guest. TODO fix this. C guest leaks when host func returns error guest panics.
```
Comment (jsturtevant) [inline src/hyperlight_host/tests/sandbox_host_tests.rs:362]: do we have an issue for this? was this the case prior?

File: src/hyperlight_common/src/flatbuffer_wrappers/function_types.rs [hunk 4]
```diff
@@ -588,123 +738,179 @@ impl TryFrom<FbFunctionCallResult<'_>> for ReturnValue {
...
-}
+// impl TryFrom<&[u8]> for ReturnValue {
+//     type Error = Error;
+//     #[cfg_attr(feature = "tracing", instrument(err(Debug), skip_all, parent = Span::current(), level= "Trace"))]
+//     fn try_from(value: &[u8]) -> Result<Self> {
+//         let function_call_result_fb = size_prefixed_root::<FbFunctionCallResult>(value)
+//             .map_err(|e| anyhow!("Failed to get ReturnValue from bytes: {:?}", e))?;
+//         function_call_result_fb.try_into()
+//     }
+// }
```
Comment (jsturtevant) [inline src/hyperlight_common/src/flatbuffer_wrappers/function_types.rs]: remove this?

File: src/hyperlight_common/src/flatbuffer_wrappers/function_types.rs [hunk 5]
```diff
@@ -22,15 +22,166 @@ use flatbuffers::size_prefixed_root;
...
+
+impl FunctionCallResult {
+    /// Encodes self into the given builder and returns the encoded data.
+    ///
+    /// # Notes
+    ///
+    /// The builder should not be reused after a call to encode, since this function
+    /// does not reset the state of the builder. If you want to reuse the builder,
+    /// you'll need to reset it first.
+    pub fn encode<'a>(&self, builder: &'a mut flatbuffers::FlatBufferBuilder) -> &'a [u8] {
```
Comment (jsturtevant) [inline src/hyperlight_common/src/flatbuffer_wrappers/function_types.rs:46]: should we have some sanity tests like we do with https://github.com/hyperlight-dev/hyperlight/blob/b419bde3cec2bb2db1b0258891f52f620e1d3ca5/src/hyperlight_common/src/flatbuffer_wrappers/function_call.rs#L283?

File: src/hyperlight_host/tests/sandbox_host_tests.rs [hunk 6]
```diff
@@ -366,10 +366,17 @@ fn host_function_error() -> Result<()> {
...
         let mut init_sandbox: MultiUseSandbox = sandbox.evolve()?;
         let msg = "Hello world";
-        let res = init_sandbox
-            .call::<i32>("GuestMethod1", msg.to_string())
-            .unwrap_err();
-        assert!(matches!(res, HyperlightError::Error(msg) if msg == "Host function error!"));
+
+        for _ in 0..1000 {
+            let res = init_sandbox
+                .call::<i32>("GuestMethod1", msg.to_string())
```
Comment (jsturtevant) [inline src/hyperlight_host/tests/sandbox_host_tests.rs:357]: could we also add a test that demonstrates how a guest would successfully handle a host function and continue processing with this new type? Do we have that already?

File: src/hyperlight_host/src/func/guest_err.rs (hunk 1 above)
Comment (jsturtevant) [reply src/hyperlight_host/src/func/guest_err.rs:35]: I was reviewing commit by commit, I saw this was moved.

File: src/hyperlight_guest_bin/src/guest_function/call.rs (hunk 2 above)
Comment (ludfjig) [reply src/hyperlight_guest_bin/src/guest_function/call.rs:86]: correct

File: src/hyperlight_common/src/flatbuffer_wrappers/function_types.rs (hunk 4 above)
Comment (ludfjig) [reply src/hyperlight_common/src/flatbuffer_wrappers/function_types.rs]: fixed

File: src/hyperlight_common/src/flatbuffer_wrappers/function_types.rs (hunk 5 above)
Comment (ludfjig) [reply src/hyperlight_common/src/flatbuffer_wrappers/function_types.rs:46]: added

File: src/hyperlight_host/tests/sandbox_host_tests.rs (hunk 6 above)
Comment (ludfjig) [reply src/hyperlight_host/tests/sandbox_host_tests.rs:357]: added

File: src/hyperlight_host/tests/sandbox_host_tests.rs (hunk 3 above)
Comment (ludfjig) [reply src/hyperlight_host/tests/sandbox_host_tests.rs:362]: This was the case prior. Feedback appreciated how to make this a nicer C-API (for all types, not just i32):
```
#[unsafe(no_mangle)]
pub extern "C" fn hl_get_host_return_value_as_Int() -> i32 {
    get_host_return_value().expect("Unable to get host return value as int")
}

```

File: src/hyperlight_host/src/sandbox/initialized_multi_use.rs [hunk 7]
```diff
@@ -493,6 +510,46 @@ mod tests {
     use crate::sandbox::SandboxConfiguration;
     use crate::{GuestBinary, HyperlightError, MultiUseSandbox, Result, UninitializedSandbox};
 
+    /// Make sure input/output buffers are properly reset after guest call (with host call)
+    #[test]
+    #[ignore = "added this test before fixing bug"]
```
Comment (jsturtevant) [inline src/hyperlight_host/src/sandbox/initialized_multi_use.rs]: should remove this?

Comment (ludfjig) [reply src/hyperlight_host/src/sandbox/initialized_multi_use.rs]: whoops

File: src/hyperlight_host/tests/sandbox_host_tests.rs (hunk 3 above)
Comment (jsturtevant) [reply src/hyperlight_host/tests/sandbox_host_tests.rs:362]: could we mimic something like wasmtime does? https://github.com/bytecodealliance/wasmtime/blob/7380932631f7784d944cb0326a6ffaaf5dac29fc/crates/c-api/src/component/val.rs#L180-L185

I don't think this needs to be a blocker as we are in this state today

**Review by jsturtevant — DISMISSED** [review]

File: docs/how-to-use-flatbuffers.md [hunk 8]
```diff
@@ -19,9 +19,3 @@ We recommend building `flatc` from source. To generate rust code, use
 ```console
 just gen-all-fbs-rust-code
 ```
-
```
Comment (danbugs) [inline docs/how-to-use-flatbuffers.md:22]: Can you update the "last version as of ..." date at the top of this file?

File: src/hyperlight_host/src/sandbox/initialized_multi_use.rs [hunk 9]
```diff
@@ -493,6 +510,43 @@ mod tests {
     use crate::sandbox::SandboxConfiguration;
     use crate::{GuestBinary, HyperlightError, MultiUseSandbox, Result, UninitializedSandbox};
 
+    /// Make sure input/output buffers are properly reset after guest call (with host call)
+    #[test]
+    fn host_func_error() {
```
Comment (danbugs) [inline src/hyperlight_host/src/sandbox/initialized_multi_use.rs:515]: nit: a better name might be `test_host_function_error_no_resource_leak`.

File: src/hyperlight_host/src/sandbox/initialized_multi_use.rs [hunk 10]
```diff
@@ -493,6 +510,43 @@ mod tests {
...
+            let result = sandbox
+                .call::<i64>(
+                    "CallGivenParamlessHostFuncThatReturnsI64",
+                    "HostError".to_string(),
+                )
+                .unwrap_err();
+
+            assert!(
+                matches!(result, HyperlightError::GuestError(code, msg) if code == ErrorCode::HostFunctionError && msg == "hi"),
+            );
```
Comment (danbugs) [inline src/hyperlight_host/src/sandbox/initialized_multi_use.rs:536]:
```suggestion
assert!(
    matches!(result, HyperlightError::GuestError(code, msg) 
        if code == ErrorCode::HostFunctionError && msg == "hi"),
    "Expected host error to be wrapped as GuestError::HostFunctionError, got {:?}", result
);
```

**Review by danbugs — COMMENTED** [review]
Awesome work. Mostly LGTM, just got some minor nits.

File: docs/how-to-use-flatbuffers.md (hunk 8 above)
Comment (ludfjig) [reply docs/how-to-use-flatbuffers.md:22]: done

**Review by adamperlin — DISMISSED** [review]
This looks good to me! It's really great that this fixed an additional fragile error handling case as well with error deserialization. One question:  have you tried reverting the behavior of host call fuzzing back to how it was before we discovered this issue, i.e., re-using the same sandbox state for each fuzzed call? Maybe we can open a follow up issue to do this?

**Comment by adamperlin** [comment]
> This looks good to me! It's really great that this fixed an additional fragile error handling case as well with error deserialization. One question: have you tried reverting the behavior of host call fuzzing back to how it was before we discovered this issue, i.e., re-using the same sandbox state for each fuzzed call? Maybe we can open a follow up issue to do this?

Added #933 to track this

File: src/hyperlight_host/tests/sandbox_host_tests.rs (hunk 3 above)
Comment (simongdavies) [reply src/hyperlight_host/tests/sandbox_host_tests.rs:362]: +1 on creating an issue for this

**Review by simongdavies — APPROVED** [review]
LGTM , this is a great fix, just +1 on creating an issue for the TODO
