### PR TITLE
Fix guest call to `halt` not dropping allocated trace data leading to memory leak 

### LINKED ISSUE #1032: Fix guest tracing memory leak when `halt` function is called
### What happened?

After a relative big number of iterations of the fuzzy test, the call to the guest function hangs, never returns.

### What did you expect to happen?

The expectation is for the fuzzy test to never make a guest function call hang or crash.

### Steps to reproduce the behavior

This issue was observed when working on running fuzzy tests that call a recursive guest function that creates spans and log events.
The test calls a guest function that makes up to 255 recursive calls and when the `halt` function is called to signal the completion of the function call, it leaks the serialized data.

### Hyperlight Version

0.11.0

### OS version

<details>

```console
On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.3 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

$ uname -a
Linux laptop 6.6.87.2-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025 x86_64 GNU/Linux

On Windows:
C:\> cmd /c ver
Not tested
````
</details>

### Additional Information

After further debugging, I found there were two issues producing this outcome:
- When the guest calls `halt` function, it wants to report the tracing data to the host, so it calls the `hyperlight-guest-tracing::guest_trace_info` function to serialize the events captured until then.
 This function returns a `Vec<u8>` and after calling the `hlt` instruction, the `hypervisor` never yields back control to the guest to correctly `drop` the allocated memory, which causes a leak.
- The problem that causes the hanging is a deadlock produced by a lock of the trace data because, at some point, the heap allocation fails which in turn generates an exception which calls `outb` function to send the same trace data to the host, which in turn tries to get the lock.

Solution:
- Change the logic to serialize the events as they are created, and only keep a buffer containing a chunk of serialized events. This removes the need to serialize/allocate when we want to send to the host.
 We can then directly send the buffer.
- Never `lock()` the trace data Mutex, instead use `try_lock()` and in case there's a place we don't know what to do, it means something terrible happened so we can panic, otherwise just skip over reporting the tracing data if needed.

### PR DESCRIPTION
**Pull request by dblnz**
## Problem
This fixes #1032.

 When the `trace_guest` feature is enabled, when a function call successfully finishes it calls `halt` which serializes all the stored events until then and returns a buffer with the data, which the `hlt` instruction provides to the host.
 However, the host doesn't continue the guest execution from the same place, so the owned variable on the stack doesn't get dropped, which leads to memory leaks.

## Solution
Avoid allocating on the stack of the `hlt` function and provide a global buffer (which lives during the entire lifetime of the VM).
Serialize each event and append it to a global, pre-allocated buffer, that when it gets filled, it automatically sends the data to the host.
In the case of `halt` call, we now return a `(ptr, len)` to the global buffer, which avoids allocations.

Things done:
- [x] Introduce `Encoder` / `Decoder` traits that define the functionality a used by the `hyperlight_guest_tracing` crate.
- [x] Implement an `EventsBatchEncoder` that batches multiple events, serializing each one individually and appending to a global buffer. The encoder takes a function as an argument that gets called whenever the buffer is filled. This function receives a reference to the buffer to be able to send it to the host. After the call is finished, the buffer gets cleared.
- [x] The encoder uses a heuristic to estimate the necessary size for the Flatbuffers buffer used to serialize each event before appending it to the global buffer (NOTE: The reason we haven't serialized in-place in the global buffer is to avoid reallocations for the global buffer in case the estimation is incorrect and by appending it overflows)
- Tests
  - [x] Added tests and fuzzying for the heuristic to ensure the logic is correct, however, even if the size is smaller than the needed size, Flatbuffers reallocs memory, which has some performance penalty, but still it doesn't fail
  - [x] Added tests for the host logic that parses the events
  - [x] Added fuzzying for end-to-end use-case. Host calls a guest function that recursively creates spans/logs, and the host parses.
  - [x] Added miri checks for `hyperlight-common` that checks the use of flatbuffers (not only tracing features)

### CODE REVIEW

File: src/hyperlight_common/src/flatbuffer_wrappers/guest_trace_data.rs [hunk 1]
```diff
@@ -130,274 +131,445 @@ pub enum GuestEvent {
...
+}
+
+impl<T: Fn(&[u8])> EventsEncoder for EventsBatchEncoderGeneric<T> {
+    /// Serialize a single GuestEvent and append it to the internal buffer.
+    /// If the appending of the serialized data exceeds buffer capacity, the
+    /// `report_full` callback is invoked with the current buffer contents,
+    /// and the buffer is cleared for new data.
+    fn encode(&mut self, event: &GuestEvent) {
+        // TODO: Estimate size more accurately
+        let estimated_size = 1024;
```
Comment (dblnz) [inline src/hyperlight_common/src/flatbuffer_wrappers/guest_trace_data.rs]: Add heuristic to estimate this.

File: src/hyperlight_host/src/sandbox/trace/context.rs [hunk 2]
```diff
@@ -396,9 +410,7 @@ impl Drop for TraceContext {
 
 #[cfg(test)]
```
Comment (dblnz) [inline src/hyperlight_host/src/sandbox/trace/context.rs:411]: Add more tests that check failure scenarios, to verify hyperlight host behavior

File: src/hyperlight_common/src/flatbuffer_wrappers/guest_trace_data.rs (hunk 1 above)
Comment (dblnz) [reply src/hyperlight_common/src/flatbuffer_wrappers/guest_trace_data.rs]: Add fuzzy tests for the heuristic to ensure it is correct

**Comment by syntactically** [comment]
I think I agree that for this specific problem making sure that the trace code does not allocate is the correct approach, since if you were to allocate for the trace buffer you could only tear it down after the vmexit after the host has had a chance to read it.

However, the description also makes me wonder whether it is a problem more generally that we are not tearing down the frame "properly"---one could imagine some e.g. guest lock release ending up in that frame through some optimisation and its loss having effects, perhaps.  Might it also make sense to try to ensure that the frame cleanup happens, perhaps by having the actual dispatch entrypoint be a tiny asm stub that just does a call and halt, so that the rust function(s) involved do properly have their frame torn down at the end before the halt is called?

**Comment by dblnz** [comment]
> I think I agree that for this specific problem making sure that the trace code does not allocate is the correct approach, since if you were to allocate for the trace buffer you could only tear it down after the vmexit after the host has had a chance to read it.
> 
> However, the description also makes me wonder whether it is a problem more generally that we are not tearing down the frame "properly"---one could imagine some e.g. guest lock release ending up in that frame through some optimisation and its loss having effects, perhaps. Might it also make sense to try to ensure that the frame cleanup happens, perhaps by having the actual dispatch entrypoint be a tiny asm stub that just does a call and halt, so that the rust function(s) involved do properly have their frame torn down at the end before the halt is called?

I think your concern is valid, and we should ensure no leaks and stack frames are properly cleaned.
This PR is specific to the tracing data, which triggered this issue faster because of the big amounts of data being allocated.
I'll open an Issue to address this separately

File: src/hyperlight_common/src/flatbuffer_wrappers/guest_trace_data.rs (hunk 1 above)
Comment (dblnz) [reply src/hyperlight_common/src/flatbuffer_wrappers/guest_trace_data.rs]: Added estimation heuristic

File: src/hyperlight_host/src/sandbox/trace/context.rs (hunk 2 above)
Comment (dblnz) [reply src/hyperlight_host/src/sandbox/trace/context.rs:411]: Added more tests and additionally miri

File: Justfile [hunk 3]
```diff
@@ -214,6 +214,12 @@ test-doc target=default-target features="":
 ### LINTING ####
 ################
 
+miri-tests:
+    rustup component add miri --toolchain nightly
```
Comment (simongdavies) [inline Justfile:218]: Curious, why did we add miri for testing for this PR?

File: Justfile [hunk 4]
```diff
@@ -214,6 +214,12 @@ test-doc target=default-target features="":
...
+    # For now only run miri tests on hyperlight-common with trace_guest feature
```
Comment (simongdavies) [inline Justfile:219]: Do we have an issue to do this?

File: Justfile [hunk 5]
```diff
@@ -342,12 +348,14 @@ bench features="":
 fuzz_memory_limit := "4096"
 
 # Fuzzes the given target
+# Uses *case* for compatibility to determine if the target is a tracing fuzzer or not
 fuzz fuzz-target:
-    cargo +nightly fuzz run {{ fuzz-target }} --release -- -rss_limit_mb={{ fuzz_memory_limit }}
+    case "{{ fuzz-target }}" in *trace*) just fuzz-trace {{ fuzz-target }} ;; *) cargo +nightly fuzz run {{ fuzz-target }} --release -- -rss_limit_mb={{ fuzz_memory_limit }} ;; esac
```
Comment (simongdavies) [inline Justfile:353]: I don't think this will work on Windows, but I just realised that we don't fuzz on Windows which I think is an issue, I'll open an issue or that

File: src/hyperlight_guest_bin/src/guest_function/call.rs [hunk 6]
```diff
@@ -138,7 +138,9 @@ pub(crate) extern "C" fn dispatch_function() {
     #[cfg(feature = "trace_guest")]
     {
         let guest_start_tsc = hyperlight_guest_tracing::invariant_tsc::read_tsc();
-        hyperlight_guest_tracing::set_start_tsc(guest_start_tsc);
+        // Reset the trace state for the new guest function call with the new start TSC
+        // This clears any existing spans/events from previous calls ensuring a clean state
+        hyperlight_guest_tracing::new_call(guest_start_tsc);
```
Comment (simongdavies) [inline src/hyperlight_guest_bin/src/guest_function/call.rs:143]: I am pretty sure that this scenario is totally broken/not possible any longer so this comment might be irrelevant but what happens if a host was to call a guest function? Not sure if we have an issue for this scenario, maybe we should..

File: src/hyperlight_guest_tracing/src/state.rs [hunk 7]
```diff
@@ -33,38 +35,49 @@ pub struct TraceBatchInfo {
...
     /// Next span ID to allocate
     next_id: AtomicU64,
-    /// Trace information that is exchanged with the host
-    data: GuestTraceData,
     /// Stack of active spans
     stack: Vec<u64>,
 }
 
-/// TODO: Change these constants to be configurable at runtime by the guest
+/// TODO: Change these constant to be configurable at runtime by the guest
```
Comment (simongdavies) [inline src/hyperlight_guest_tracing/src/state.rs:46]: Do we have an issue for this?

File: Justfile (hunk 3 above)
Comment (dblnz) [reply Justfile:218]: I wanted to make sure the things I added for tracing don't produce UB.
It was not a hard requirement. Do you think we don't need it?

File: Justfile (hunk 4 above)
Comment (dblnz) [reply Justfile:219]: I tried running for `hyperlight-host` and got some errors, which weren't related to this. I'll open an issue for this

File: src/hyperlight_guest_bin/src/guest_function/call.rs (hunk 6 above)
Comment (dblnz) [reply src/hyperlight_guest_bin/src/guest_function/call.rs:143]: I am not sure if I understand your concern.
 This, for example, makes sure that after a guest runs `hlt`, a new guest function call starts with an empty buffer. So we don't end up reporting the same events to the host multiple times

File: src/hyperlight_guest_tracing/src/state.rs (hunk 7 above)
Comment (dblnz) [reply src/hyperlight_guest_tracing/src/state.rs:46]: Yes, it is part of an issue where I'll address guest trace buffer configuration

File: Justfile (hunk 3 above)
Comment (simongdavies) [reply Justfile:218]: No, was just wondering what miri gave us that we needed here

File: src/hyperlight_guest_bin/src/guest_function/call.rs (hunk 6 above)
Comment (simongdavies) [reply src/hyperlight_guest_bin/src/guest_function/call.rs:143]: Ideally we could allow host->guest-func->host-func->guest-func (i.e. the host re-enters the guest before the original guest call completes, I was wondering if the trace would flow properly in that case (I don't think it would) but I think its a hypothetical anyway because I dont think we ever (re-)enabled the scenario anyway.

File: Justfile (hunk 4 above)
Comment (dblnz) [reply Justfile:219]: Created issue https://github.com/hyperlight-dev/hyperlight/issues/1083
